## NumPy

In [177]:
import numpy as np

### Single-dimensional Array

In [178]:
l1 = [10, 20, 30, 40, 50]

In [179]:
a1 = np.array(l1)
a1

array([10, 20, 30, 40, 50])

In [180]:
type(a1)

numpy.ndarray

### Multi-dimensional Array

In [181]:
a2 = np.array([[1, 2, 3, 4, 5], [5, 4, 3, 2, 1]])
a2

array([[1, 2, 3, 4, 5],
       [5, 4, 3, 2, 1]])

In [182]:
type(a2)

numpy.ndarray

### Initializing NumPy Array

In [183]:
a3 = np.zeros((2, 3))
a3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [184]:
type(a3)

numpy.ndarray

In [185]:
a4 = np.zeros((10, 10))
a4

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

### Initializing NumPy Array with Same Number

In [186]:
a5 = np.full((3, 3), 10)
a5

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

### Initializing NumPy Array with a Range

In [187]:
a6 = np.arange(10, 50)
a6

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [188]:
a7 = np.arange(0, 500, 10)
a7

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120,
       130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250,
       260, 270, 280, 290, 300, 310, 320, 330, 340, 350, 360, 370, 380,
       390, 400, 410, 420, 430, 440, 450, 460, 470, 480, 490])

### Initializing NumPy Array with Random Numbers

In [189]:
a8 = np.random.randint(1, 100, 10)
a8

array([72, 74, 90, 12, 68, 99, 32, 10, 41, 41])

### Checking the Shape of NumPy Arrays

In [190]:
a9 = np.array([[1, 2, 3, 4], [4, 3, 2, 1]])
a9

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

In [191]:
a9.shape

(2, 4)

In [192]:
a9.shape = (4, 2)

In [193]:
a9

array([[1, 2],
       [3, 4],
       [4, 3],
       [2, 1]])

In [194]:
a9.shape

(4, 2)

In [195]:
a9.shape = (8, 1)
a9

array([[1],
       [2],
       [3],
       [4],
       [4],
       [3],
       [2],
       [1]])

In [196]:
a9.shape

(8, 1)

### Joining NumPy Arrays

In [197]:
n1 = np.array([1, 2, 3])
n2 = np.array([4, 5, 6])

In [198]:
np.vstack((n1, n2))

array([[1, 2, 3],
       [4, 5, 6]])

In [199]:
np.hstack((n1, n2))

array([1, 2, 3, 4, 5, 6])

In [200]:
np.column_stack((n1, n2))

array([[1, 4],
       [2, 5],
       [3, 6]])

### NumPy Intersection, Union & Difference

In [201]:
n1 = np.array([10, 20, 30, 40, 50, 60])
n2 = np.array([50, 60, 70, 80, 90, 100])

In [202]:
np.intersect1d(n1, n2)

array([50, 60])

In [203]:
np.setdiff1d(n1, n2)

array([10, 20, 30, 40])

In [204]:
np.setdiff1d(n2, n1)

array([ 70,  80,  90, 100])

In [205]:
np.union1d(n1, n2)

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

### Addition of NumPy Arrays

In [206]:
n1 = np.array([10, 20])
n2 = np.array([30, 40])

In [207]:
np.sum([n1, n2])

100

In [208]:
np.sum([n1, n2], 0)

array([40, 60])

In [209]:
np.sum([n1, n2], 1)

array([30, 70])

### NumPy Array Matehmatics

In [210]:
n1 = np.array([10, 20, 30])

In [211]:
n1 + 5

array([15, 25, 35])

In [212]:
n1 - 5

array([ 5, 15, 25])

In [213]:
n1 * 5

array([ 50, 100, 150])

In [214]:
n1 / 5

array([2., 4., 6.])

### NumPy Math Functions

In [215]:
n1 = np.random.randint(1, 50, 10)

In [216]:
n1

array([ 9, 21, 42, 42, 45, 15,  7, 24, 49, 33])

In [217]:
np.mean(n1)

28.7

In [218]:
np.median(n1)

28.5

In [219]:
np.std(n1)

14.758387445788243

### NumPy Save & Load

In [220]:
n1 = np.array([10, 20, 30, 40, 50])
n1

array([10, 20, 30, 40, 50])

In [221]:
np.save("myarray", n1)

In [222]:
new_n1 = np.load("myarray.npy")

In [223]:
new_n1

array([10, 20, 30, 40, 50])